version: "3"

services:
  # Defines a service name
  workspace:
    build:
      # Sets the build context to the current directory
      context: .
      # Specifies the Dockerfile to use for the build
      dockerfile: .docker/Dockerfile.app
      # Specifies build-time variables (ARGs)
      args:
        ARG_BUILD_FROM: $BUILD_FROM
        ARG_USERNAME: $CONTAINER_USERNAME
        ARG_WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
        ARG_APP_SOURCE_REPO: $APP_SOURCE_REPO
        ARG_APP_INSTALL_ROOT: $APP_INSTALL_ROOT
        ARG_APP_CLONE_DIRNAME: $APP_CLONE_DIRNAME
        ARG_APP_SOURCE_BRANCH: $APP_SOURCE_BRANCH
        ARG_APP_SERVICE_NAME: $APP_SERVICE_NAME
        ARG_BENTOML_HOME: $CONTAINER_BENTOML_HOME
    # Sets the image name for the built image
    image: $IMAGE_NAME:$IMAGE_TAG
    # Sets the hostname of the container
    hostname: $CONTAINER_HOSTNAME
    entrypoint:
      # Specifies the command to be executed when the container is run
      - /bin/bash
      - $CONTAINER_LAUNCH_SCRIPT
    # set the environment variables
    environment:
      USER_UID: $CONTAINER_USER_UID
      WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
      IMAGE_VARIANT: $IMAGE_VARIANT
      GIT_COMMIT_GPGSIGN: $GIT_COMMIT_GPGSIGN
      BENTOML_HOME: $CONTAINER_BENTOML_HOME
      HF_ACCESS_TOKEN: $HF_ACCESS_TOKEN
      HUGGING_FACE_HUB_TOKEN: $HUGGING_FACE_HUB_TOKEN
      OPENLLM_MODEL_NAME: $OPENLLM_MODEL_NAME
      OPENLLM_MODEL_ID: $OPENLLM_MODEL_ID
      OPENLLM_BACKEND: $OPENLLM_BACKEND
      OPENLLM_DO_NOT_TRACK: $OPENLLM_DO_NOT_TRACK
      SSH_PUB_KEY: $SSH_PUB_KEY
      HF_HOME: $APP_HF_HOME
    ulimits:
      # Sets the stack size and memory lock limits
      stack: 67108864
      memlock: -1
    # Allows the container to use the host's IPC namespace
    ipc: $CONTAINER_IPC
    ports:
      # Maps the container's SSH and Web service ports to the host's ports
      - "$HOST_SSH_PORT:$CONTAINER_SSH_PORT"
      - "$HOST_WEB_SVC_PORT:$CONTAINER_WEB_SVC_PORT"
    volumes:
      # Maps directories from the host to the container
      - "$HOST_SCRIPTS_DIR:$CONTAINER_WORKSPACE_ROOT/scripts"
      - "$HOST_BENTOML_HOME:$CONTAINER_BENTOML_HOME"
      - "$HOST_HF_HOME:$CONTAINER_HF_HOME"
    deploy:
      resources:
        reservations:
          devices:
            # Reserves the specified GPU for the container
            - driver: nvidia
              device_ids: ["${CONTAINER_CUDA_DEVICE_ID}"]
              capabilities: [gpu]
  playgroud:
    # Sets the image name for the built image
    image: ghcr.io/bentoml/openllm-ui-clojure:latest
    ports:
      # Maps the container's SSH and Web service ports to the host's ports
      - "$HOST_WEB_UI_PORT:$CONTAINER_WEB_UI_PORT"
networks:
  default:
    # Sets the name of the default network and makes it external
    name: $CONTAINER_NETWORK_NAME
    external: true
