version: "3"

services:
  # Defines a service name
  playgroud:
    # Sets the image name for the built image
    image: ghcr.io/bentoml/openllm-ui-clojure:latest
    ports:
      # Maps the container's SSH and Web service ports to the host's ports
      - "$HOST_WEB_UI_PORT:$CONTAINER_WEB_UI_PORT"
networks:
  default:
    # Sets the name of the default network and makes it external
    name: $CONTAINER_NETWORK_NAME
    external: true
